
on: [push, pull_request, workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@2.1.4
      - run: |
          go mod tidy
          cd example
          go build .
          ./example
