
on: [push, pull_request, workflow_dispatch]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: build and download
        run: go install ./...
        
      - name: execute
        run: get
          
